baseurl      = "https://www.shagun.xyz/"
title        = "Shagun Attri"
languageCode = "en-US"
theme        = "hello-friend-ng"
DefaultContentLanguage = "en"
copyright = "This work is licensed under Creative Commons Attribution 4.0 International License."
enableGitInfo   = true

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

paginate = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
  [markup.highlight]
    style = "native"
    guessSyntax = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  dnd = "dnd"

 [author]
  name = "shagun attri"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02"
  defaultTheme = "light"
  EnableThemeToggle = true
  description = "Shagun Attri's blog sharing perspectives and insights on cybersecurity, startups, and software development."
  disableReadOtherPosts = false
  homeSubtitle = "Sharing Perspectives on Cybersecurity & Startups!"
  keywords = "cybersecurity, startups, software development, infosec, technology, blog, shagun attri"
  contentTypeName = "posts"
  gitUrl = "https://github.com/shagunattri/site/commit/"
  images = ["/static/image1.png"]

  [params.Logo]
    logoCursorColor = "#4FC3F7"

[params.Portrait]
  Path = "images/cover.jpg"
  Alt = "Shagun"
  MaxWidth = "150px"

[languages]
  [languages.en]
    [languages.en.params]
      logoText = "Shagun Attri"
      logoHomeLink = "/"
      title = "Shagun's üì¶"
      subtitle = ""
      keywords = ""
      copyright = "<a href='https://creativecommons.org/licenses/by/4.0/' target='_blank'>CC-BY 4.0</a>"
      readOtherPosts = "‚Üê Prev | Read more | Next ‚Üí"

[menu]
   [[menu.main]]
    identifier = "projects"
    name       = "projects"
    url        = "/projects/"
   [[menu.main]]
    identifier = "blog"
    name       = "blog"
    url        = "/blog/"
  [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "about/"


  [[params.social]]
    name = "email"
    url  = "mailto:mail@shagun.xyz"
  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/shagunattri"
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/shagunattri_"        
  [[params.social]]
    name = "instagram"
    url  = "https://instagram.com/shagunattri_"   
  [[params.social]]
    name = "github"
    url  = "https://github.com/shagunattri"